#!/bin/bash

gfortran -o toymodel toymodel.F90 && ./toymodel

mpif90 -g -C  -DMODEL_PARALLEL -o toymodel toymodel.F90 && mpirun -np 4 toymodel
mpif90 -g -C -DOAK -DMODEL_PARALLEL -o toymodel toymodel.F90 && mpirun -np 4 toymodel

mpif90 -g -C -DOAK -o toymodel toymodel.F90 && mpirun -np 4 toymodel