db = [];

[db(1).time,db(1).files] = filetlist2('ostia_ice_*.nc','ostia_ice_YYYYMMDD.nc');


db(1).ncname = 'sea_ice_fraction';

[db(1).time,db(1).files] = filetlist2('ostia_sst_????????.nc','xxxxx_xxx_YYYYMMDD.xx');
db(1).ncname = 'analysed_sst';
db(1).variables  = 'tn';
db(1).names      = 'temp';
db(1).gridX      = 'ostia_sst_grid.nc#lonp';
db(1).gridY      = 'ostia_sst_grid.nc#lat';
db(1).gridZ      = 5;
db(1).rmse       = 'ostia_sst_20070111.nc#err';





fid = fopen('assim_obs.init','w');


fprintf(fid,'# generated by %s\n\n',mfilename);

%time = mjd(2007,1,10):1:mjd(2007,1,31);
time = mjd(2007,2,1):1:mjd(2007,2,28);

for n = 1:length(time);
    
    date = gregd2(time(n),'YYYYMMDD');
    prefix = sprintf('Obs%03g.',n);
    putinitval(fid,[prefix 'time'],gregd2(time(n),'YYYY-MM-DDThh:mm:ss'));
    putinitval(fid,[prefix 'variables'],{                          'tn',                                  'icec'});
    
    putinitval(fid,[prefix 'names'],{'temp',                                  'icec'});
    putinitval(fid,[prefix 'gridX'],{'ostia_sst_grid.nc#lonp',                'ostia_sst_grid.nc#lonp'});
    putinitval(fid,[prefix 'gridY'],{'ostia_sst_grid.nc#lat',                 'ostia_sst_grid.nc#lat'});
    putinitval(fid,[prefix 'gridZ.const'],{                                   5,                                    0.1 });
    putinitval(fid,[prefix 'value'],{['ostia_sst_' date '.nc#analysed_sst'],['ostia_ice_' date '.nc#sea_ice_fraction']});
    putinitval(fid,[prefix 'mask'],{['ostia_sst_' date '.nc#analysed_sst'], ['ostia_ice_' date '.nc#sea_ice_fraction']});
    putinitval(fid,[prefix 'rmse'],{         ['ostia_sst_' date '.nc#err'],                               'ice.err'});
    
    prefix = sprintf('Diag%03g.',n);
    putinitval(fid,[prefix 'Hxf'       ],{                            'xf.sst',                                'xf.ice'});
    putinitval(fid,[prefix 'Hxa'       ],{                            'xa.sst',                                'xa.ice'});
    putinitval(fid,[prefix 'yo'        ],{                            'yo.sst',                                'yo.ice'});
    putinitval(fid,[prefix 'invsqrtR'  ],{                      'invsqrtR.sst',                          'invsqrtR.ice'});
    putinitval(fid,[prefix 'stddevHxf' ],{                     'stddevHxf.sst',                         'stddevHxf.ice'});
    putinitval(fid,[prefix 'stddevHxa' ],{                     'stddevHxa.sst',                         'stddevHxa.ice'});
    
    putinitval(fid,[prefix 'path' ],sprintf('Analysis%03g/',n));
    putinitval(fid,sprintf('Analysis%03g.path',n),sprintf('Analysis%03g/',n));
    fprintf(fid,'\n#------------------------------------------------------------------------------------\n\n');
    
end


fclose(fid);


