

fun = @(t0,t1,x,forcing) [x([2:end 1])];

t0 = 0;
t1 = 1;

model = ModelFun(1,fun);

x = randn(1,100);

simulation = run(model,t0,t1,x,[]);
xn = result(model,simulation);

xnr = fun(t0,t1,x);
assert(rms(xnr,xn) < 1e-11);

return

scheduler = Scheduler();
script = '-N analysis -pe snode 4  ~/bin/submit_roms_hf_sst.sh ~/Models/LigurianSea/roms-only-bc-adv/oceanO';
template = '/u/abarth/tmp/LigurianSea/Ens-bc-wind-July2010_test/Common/ocean_ls.in';
dt = 150; %s

param = struct(...
  'NtileI',4,...
  'NtileJ',2,...
  'nhis',100,...
  'navg',100 ...
    );


model = ModelROMS(dt,script,template,param,scheduler)
initgrid
mask = ones(10,10);

path = '/u/abarth/tmp/LigurianSea/Ens-bc-wind-July2010_test/Ens002/';
icname = 'ic.nc';
variables = {[icname '#zeta'],...
             [icname '#temp'],...
             [icname '#salt'],...
             [icname '#u'],...
             [icname '#v'],...
             [icname '#ubar'],...
             [icname '#vbar']};

ic = SVector(path,variables,{mask,mask},1);
t0 = 55383;
t1 = t0+10*dt/24/60/60;


varn = {'wind.nc#Uwind',...
        'wind.nc#Vwind',...
        'bc.nc#zeta_south',...
        'bc.nc#ubar_south',...
        'bc.nc#vbar_south',...
        'bc.nc#temp_south',...
        'bc.nc#salt_south',...
        'bc.nc#u_south',...
        'bc.nc#v_south',...
        'bc.nc#zeta_west',...
        'bc.nc#ubar_west',...
        'bc.nc#vbar_west',...
        'bc.nc#temp_west',...
        'bc.nc#salt_west',...
        'bc.nc#u_west',...
        'bc.nc#v_west',...
        'pert.nc#uvPert'...
       };

forcing = SVector(path,varn,{domain.mask,domain.mask},1);

simulation = run(model,t0,t1,ic,forcing);
xn = result(model,simulation);
